using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace SnuggleMonsters
{
    /// <summary>
    /// Controls the dress-up mode in the Bedroom scene.
    /// Manages equipping and removing clothing items (hats, scarves, glasses)
    /// on the monster via dedicated attach points.
    /// </summary>
    public class DressUpController : MonoBehaviour
    {
        // ──────────────────────────────────────────────────────────────────
        //  Serialized Fields — Clothing Options
        // ──────────────────────────────────────────────────────────────────

        [Header("Clothing Options")]
        [Tooltip("All available hat options.")]
        public ClothingSO[] allHatOptions;

        [Tooltip("All available scarf options.")]
        public ClothingSO[] allScarfOptions;

        [Tooltip("All available glasses options.")]
        public ClothingSO[] allGlassesOptions;

        // ──────────────────────────────────────────────────────────────────
        //  Serialized Fields — Attach Points
        // ──────────────────────────────────────────────────────────────────

        [Header("Attach Points")]
        [Tooltip("Child transform on the monster where hats are placed.")]
        public Transform hatAttachPoint;

        [Tooltip("Child transform on the monster where scarves are placed.")]
        public Transform scarfAttachPoint;

        [Tooltip("Child transform on the monster where glasses are placed.")]
        public Transform glassesAttachPoint;

        // ──────────────────────────────────────────────────────────────────
        //  Serialized Fields — UI References
        // ──────────────────────────────────────────────────────────────────

        [Header("UI References")]
        [Tooltip("Array of UI buttons for clothing items. Should be pre-populated in the inspector or generated by dress-up panel setup.")]
        public Button[] clothingButtons;

        [Tooltip("Button to clear all clothing from the monster.")]
        public Button clearButton;

        // ──────────────────────────────────────────────────────────────────
        //  Private State
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Lookup from ClothingType to its attach point transform.
        /// </summary>
        private Dictionary<ClothingType, Transform> _attachPoints;

        /// <summary>
        /// Currently equipped clothing items, keyed by ClothingType.
        /// </summary>
        private Dictionary<ClothingType, ClothingSO> _equippedItems;

        /// <summary>
        /// Currently spawned clothing visual instances, keyed by ClothingType.
        /// </summary>
        private Dictionary<ClothingType, GameObject> _equippedInstances;

        // ──────────────────────────────────────────────────────────────────
        //  Unity Lifecycle
        // ──────────────────────────────────────────────────────────────────

        private void Awake()
        {
            // Initialise dictionaries
            _attachPoints = new Dictionary<ClothingType, Transform>
            {
                { ClothingType.Hat, hatAttachPoint },
                { ClothingType.Scarf, scarfAttachPoint },
                { ClothingType.Glasses, glassesAttachPoint }
            };

            _equippedItems = new Dictionary<ClothingType, ClothingSO>();
            _equippedInstances = new Dictionary<ClothingType, GameObject>();
        }

        private void OnEnable()
        {
            // Populate clothing buttons with all available items
            PopulateClothingButtons();

            // Wire up clear button
            if (clearButton != null)
            {
                clearButton.onClick.RemoveAllListeners();
                clearButton.onClick.AddListener(ClearAll);
            }
        }

        private void OnDisable()
        {
            if (clearButton != null)
                clearButton.onClick.RemoveListener(ClearAll);
        }

        // ──────────────────────────────────────────────────────────────────
        //  Initialisation
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Populates the clothing buttons array with entries for all available
        /// clothing items across all categories. Each button is configured with
        /// a preview image and a click handler.
        /// </summary>
        private void PopulateClothingButtons()
        {
            if (clothingButtons == null || clothingButtons.Length == 0)
            {
                Debug.LogWarning("[DressUpController] No clothing buttons assigned — skipping population.");
                return;
            }

            // Collect all clothing items into a flat list
            List<ClothingSO> allItems = new List<ClothingSO>();
            if (allHatOptions != null) allItems.AddRange(allHatOptions);
            if (allScarfOptions != null) allItems.AddRange(allScarfOptions);
            if (allGlassesOptions != null) allItems.AddRange(allGlassesOptions);

            // Assign items to buttons (one per button, or leave empty)
            for (int i = 0; i < clothingButtons.Length; i++)
            {
                if (clothingButtons[i] == null)
                    continue;

                if (i < allItems.Count && allItems[i] != null)
                {
                    ClothingSO item = allItems[i];
                    ConfigureButton(clothingButtons[i], item);
                }
                else
                {
                    // Disable unused buttons
                    clothingButtons[i].gameObject.SetActive(false);
                }
            }
        }

        /// <summary>
        /// Configures a single button to represent a clothing item.
        /// Sets the preview sprite and click handler.
        /// </summary>
        private void ConfigureButton(Button button, ClothingSO item)
        {
            // Set preview sprite
            Image buttonImage = button.GetComponent<Image>();
            if (buttonImage != null && item.sprite != null)
            {
                buttonImage.sprite = item.sprite;
                buttonImage.color = item.tintColor;
            }

            // Set click handler
            button.onClick.RemoveAllListeners();
            button.onClick.AddListener(() => OnSelectClothing(item));

            // Make sure the button is visible
            button.gameObject.SetActive(true);
        }

        // ──────────────────────────────────────────────────────────────────
        //  Clothing Selection & Removal
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Equips the given clothing item to its appropriate slot.
        /// If the slot is already occupied, the existing item is replaced.
        /// </summary>
        /// <param name="item">The clothing item to equip.</param>
        public void OnSelectClothing(ClothingSO item)
        {
            if (item == null)
            {
                Debug.LogWarning("[DressUpController] Cannot equip null clothing item.");
                return;
            }

            ClothingType slot = item.clothingType;

            // If this slot has an item already, remove it first
            if (_equippedItems.ContainsKey(slot) && _equippedItems[slot] != null)
            {
                OnRemoveClothing(_equippedItems[slot]);
            }

            // Find the attach point for this slot
            Transform attachPoint = GetAttachPoint(slot);
            if (attachPoint == null)
            {
                Debug.LogWarning($"[DressUpController] No attach point for slot '{slot}' — skipping equip.");
                return;
            }

            // Create a visual representation
            // We instantiate a simple GameObject: if the ClothingSO has a sprite,
            // we create a sprite object; otherwise a placeholder coloured cube.
            GameObject clothingVisual = CreateClothingVisual(item, attachPoint);

            // Store references
            _equippedItems[slot] = item;
            _equippedInstances[slot] = clothingVisual;

            Debug.Log($"[DressUpController] Equipped '{item.displayName}' to {slot} slot.");
        }

        /// <summary>
        /// Removes the given clothing item from its slot and destroys the visual.
        /// </summary>
        /// <param name="item">The clothing item to remove.</param>
        public void OnRemoveClothing(ClothingSO item)
        {
            if (item == null)
            {
                Debug.LogWarning("[DressUpController] Cannot remove null clothing item.");
                return;
            }

            ClothingType slot = item.clothingType;

            // Destroy the visual instance
            if (_equippedInstances.TryGetValue(slot, out GameObject instance) && instance != null)
            {
                Destroy(instance);
            }

            // Clear the lookup
            _equippedInstances.Remove(slot);
            _equippedItems.Remove(slot);

            Debug.Log($"[DressUpController] Removed '{item.displayName}' from {slot} slot.");
        }

        /// <summary>
        /// Removes all clothing items from the monster.
        /// </summary>
        public void ClearAll()
        {
            // Collect all equipped slots so we can iterate safely while modifying the dictionary
            List<ClothingType> slots = new List<ClothingType>(_equippedItems.Keys);
            foreach (ClothingType slot in slots)
            {
                if (_equippedItems.TryGetValue(slot, out ClothingSO item) && item != null)
                {
                    OnRemoveClothing(item);
                }
            }

            Debug.Log("[DressUpController] Cleared all clothing.");
        }

        // ──────────────────────────────────────────────────────────────────
        //  Helpers
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Returns the attach point transform for the given clothing type.
        /// Falls back to this transform if none is assigned.
        /// </summary>
        private Transform GetAttachPoint(ClothingType type)
        {
            if (_attachPoints.TryGetValue(type, out Transform point) && point != null)
                return point;

            // Fallback: try the type name as a child name
            Transform fallback = transform.Find(type.ToString());
            if (fallback != null)
            {
                _attachPoints[type] = fallback;
                return fallback;
            }

            return transform;
        }

        /// <summary>
        /// Creates a visual GameObject representing the clothing item,
        /// parented to the attach point with the specified offset.
        /// </summary>
        private GameObject CreateClothingVisual(ClothingSO item, Transform attachPoint)
        {
            GameObject visual;

            if (item.sprite != null)
            {
                // Use a SpriteRenderer to display the clothing sprite
                visual = new GameObject(item.displayName + "_Visual");
                visual.transform.SetParent(attachPoint, false);
                visual.transform.localPosition = item.attachOffset;

                SpriteRenderer renderer = visual.AddComponent<SpriteRenderer>();
                renderer.sprite = item.sprite;
                renderer.color = item.tintColor;
                renderer.sortingOrder = 10; // Above monster body
            }
            else
            {
                // Fallback: create a coloured cube placeholder
                visual = GameObject.CreatePrimitive(PrimitiveType.Cube);
                visual.name = item.displayName + "_Placeholder";
                visual.transform.SetParent(attachPoint, false);
                visual.transform.localPosition = item.attachOffset;
                visual.transform.localScale = Vector3.one * 0.3f;

                Renderer renderer = visual.GetComponent<Renderer>();
                if (renderer != null)
                    renderer.material.color = item.tintColor;
            }

            return visual;
        }

        /// <summary>
        /// Returns whether the given clothing type slot is currently occupied.
        /// </summary>
        public bool IsSlotOccupied(ClothingType type)
        {
            return _equippedItems.ContainsKey(type) && _equippedItems[type] != null;
        }

        /// <summary>
        /// Returns the currently equipped item for the given slot, or null.
        /// </summary>
        public ClothingSO GetEquippedItem(ClothingType type)
        {
            _equippedItems.TryGetValue(type, out ClothingSO item);
            return item;
        }
    }
}